---
- name: Generate join command for workers
  command: kubeadm token create --print-join-command
  register: join_command_workers

- name: Copy join command for workers to local file
  local_action:
    module: copy
    content: "{{ join_command_workers.stdout_lines[0] }}"
    dest: /tmp/join-command-workers
    mode: 0744
