k8sServiceHost: localhost
k8sServicePort: 6443
ipam:
  mode: kubernetes
kubeProxyReplacement: strict
bpf:
  hostLegacyRouting: false
  lbExternalClusterIP: true
  masquerade: true
bandwidthManager:
  enabled: true
externalIPs:
  enabled: true
gatewayAPI:
  enabled: false
hubble:
  enabled: true
  listenAddress: :4244
  metrics:
    enableOpenMetrics: true
    enabled:
    - dns:query;ignoreAAAA
    - drop
    - flow
    - flows-to-world
    - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
    - icmp
    - port-distribution
    - tcp
  relay:
    enabled: true
  ui:
    enabled: true
prometheus:
  enabled: true
operator:
  prometheus:
    enabled: false
tunnel: vxlan