all:
  hosts:
    node1:
      ansible_host: 10.10.19.10
      ansible_name: kubernetes-01
    node2:
      ansible_host: 10.10.19.11
      ansible_name: kubernetes-02
    node3:
      ansible_host: 10.10.19.12
      ansible_name: kubernetes-03
  children:
    control_plane:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        control_plane:
