---
- name: Set DPKG architecture
  set_fact:
    dpkg_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

- name: Add apt signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  environment: "{{ proxy | default({}) }}"

- name: Add apt repository
  apt_repository:
    repo: deb [arch={{ dpkg_arch }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker
  environment: "{{ proxy | default({}) }}"

- name: Install packages
  apt:
    name: containerd.io
    state: latest
  environment: "{{ proxy | default({}) }}"

- name: Disable auto update
  dpkg_selections:
    name: containerd.io
    selection: hold

- name: Comment out APT repository
  replace:
    path: /etc/apt/sources.list.d/docker.list
    regexp: '^deb'
    replace: '# deb'
  when: not containerd.source_list | default(true)
