---
- name: Create timesyncd directories
  file:
    path: /etc/systemd/timesyncd.conf.d
    state: directory
    mode: 0755

- name: Set NTP servers
  template:
    src: templates/timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf.d/cloud-init.conf
  notify:
  - Restart Timesyncd

- name: Set timezone
  timezone:
    name: "{{ timesync.zone }}"
